import jsPDF from 'jspdf';
import { getScanHistory } from './storage';

export async function generateDoctorReport(profileName = "Patient") {
  const history = await getScanHistory();
  
  // Create new PDF (portrait, points, A4)
  const doc = new jsPDF();
  
  // Header
  doc.setFillColor(13, 148, 136); // Teal Primary
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text("Kali Medical Report", 20, 25);
  
  // Patient Info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.text(`Patient Name: ${profileName}`, 20, 60);
  doc.text(`Generation Date: ${new Date().toLocaleDateString()}`, 20, 70);
  
  // Scan Summary
  doc.setFontSize(16);
  doc.text("Scan History Summary", 20, 90);
  
  if (history.length === 0) {
    doc.setFontSize(12);
    doc.text("No scans recorded yet.", 20, 105);
  } else {
    // Basic Table Header
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text("Date", 20, 105);
    doc.text("Type", 60, 105);
    doc.text("Score", 100, 105);
    doc.text("Category", 130, 105);
    doc.text("Confidence", 170, 105);
    
    doc.line(20, 108, 190, 108);
    
    doc.setFont('helvetica', 'normal');
    let yPos = 115;
    
    // Limits
    const reportHistory = history.slice(0, 20); // Last 20 scans
    
    reportHistory.forEach(item => {
      const d = new Date(item.date).toLocaleDateString();
      doc.text(d, 20, yPos);
      doc.text(item.scanType || '-', 60, yPos);
      doc.text(item.score.toString(), 100, yPos);
      doc.text(item.category, 130, yPos);
      doc.text(item.confidence ? `${item.confidence}%` : '-', 170, yPos);
      
      yPos += 10;
      
      // Page break if needed
      if (yPos > 280) {
        doc.addPage();
        yPos = 20;
      }
    });
  }

  // Footer Disclaimer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Disclaimer: This report is generated by a heuristic algorithm app and is not a clinical diagnosis. Consult a physician.", 20, 290);
  
  doc.save(`Kali_Report_${profileName.replace(/\s+/g, '_')}.pdf`);
}
